name: GitHub Actions Webapp
on: [push]
jobs:
  web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
     
      - name: Build 
        run: npm run build
        working-directory: .
      - run: echo "Finished"  
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: my-app-name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: somefolder
    
